### ISSUE TITLE
"Timed out connecting to Loki"

### ISSUE THREAD

**Issue by loewelion** [grafana/prometheus-arduino#13]
I followed this tutorial [https://grafana.com/blog/2021/07/19/iot-at-your-home-work-or-data-center-with-prometheus-metrics-and-grafana-cloud/](url) to get the ESP32 running. After I fixed the problem with the wrong certificate #10  the ESP was finnaly able to connect successfully but is getting always a timeout:

`1675064609430`
`Begin serialization: Free Heap: 240572`
`Bytes used for serialization: 148`
`After serialization: Free Heap: 240572`
`After Compression Init: Free Heap: 240044`
`Required buffer size for compression: 204`
`Compressed Len: 132`
`After Compression: Free Heap: 240572`
`Sending To Prometheus`
`Connecting...`
`Connected.`
`Sent, waiting for response`
`Timed out connecting to Loki`
`1675064628071`

I kicked out everything out related to the sensors and just tried to write the system time to the Grafan cloud. Things that I already tried:

- Generate different API tokens with different roles (admin, metricsPublisher,...)
- Change the timeout values in the library.
- 3 different WiFi networks did not change anything. 
- Tried Loki and Prometheus logins/API keys

Any suggestion or deeper debugging information would be higly apreciated. I don' t get the point what is going wrong.

**Comment by ggmanugg** [comment]
Same behavior here

**Comment by FGalvagno** [comment]
Did you manage to fix the problem? I'm having the same issue

**Comment by fridgepoet** [comment]
I saw this behavior as well and resolved it by using an updated certificate.
I opened a PR for this fix, you all can try out the new certificate locally and see if that resolves it for you if you're in a hurry.
https://github.com/grafana/prometheus-arduino/pull/15/files
